name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    strategy:
      matrix:
        env:
          - { os: 'ubuntu-22.04', node: 18 }
          - { os: 'windows-2022', node: 18 }
          - { os: 'macos-12', node: 18 }
    runs-on: ${{ matrix.env.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.env.node }}
          cache: npm
      - run: npm install --no-save vitest jsdom
      - run: node node_modules/vitest/dist/cli.js run
